### ISSUE TITLE
Cannot re-create workload cluster with same name

### ISSUE THREAD

**Issue by rizblie** [aws-samples/eks-multi-cluster-gitops#55]
If a workload cluster is removed, and then re-created with the same name, the cluster secret `cluster-name-eks-connection`is not created and this causes reconciliation to fail.

While this is an improbable scenario, it does suggest that the cleanup process following the deletion of the cluster is missing something.

**Comment by iamahgoub** [comment]
Cleaning-up pending issues; I retested this scenario lately, and it worked. Please bear in mind that Crossplane does not maintain a dependency graph for compositions, so it may happen that one of the resources that is part of a composition is deleted before a dependent resource is deleted; this will lead to inability to delete the dependent resource unless you manually removed `finalizer` from the object.

After you delete a cluster, you are advised to manually check the corresponding resources in the management and make sure all are deleted before you recreate it with the same name. If a dependent is not deleted and stuck because the resource it is depending on is already deleted, you need to remove the `finalizer`, and manually delete (or just wait for a minute or so, and it will be automatically deleted).
